source ~/dev/dotfiles/zsh/omzrc

# Prefer neovim
alias vim=nvim
alias tm='tmux new -As base'
alias sz='source ~/dev/dotfiles/zsh/zshrc'


if [ -f ~/dev/dotfiles/zsh/gitaliases ]; then
	source ~/dev/dotfiles/zsh/gitaliases
fi

if [ -f ~/dev/dotfiles/zsh/gitfns ]; then
	source ~/dev/dotfiles/zsh/gitfns
fi


if [ -f ~/dev/dotfiles/zsh/workrc ]; then
	source ~/dev/dotfiles/zsh/workrc
fi

# Yarn install with compression level zero
# Needs local chromium installed first
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
