source ~/dev/dotfiles/zsh/omzrc

# Prefer neovim
alias vim=nvim
alias tm='tmux new -As base'
alias sz='source ~/dev/dotfiles/zsh/zshrc'


if [ -f ~/dev/dotfiles/zsh/gitaliases ]; then
	source ~/dev/dotfiles/zsh/gitaliases
fi

if [ -f ~/dev/dotfiles/zsh/gitfns ]; then
	source ~/dev/dotfiles/zsh/gitfns
fi


if [ -f ~/dev/dotfiles/zsh/workrc ]; then
	source ~/dev/dotfiles/zsh/workrc
fi
